export type StorageKeyTypes =
  | 'MAXuser'
  | 'userToken'
  | 'site'
  | 'org'
  | 'user'
  | 'apiUrl'
  | 'loginDate';

export type InputTypes = 'checkbox' | 'radio' | 'text' | 'number' | 'dropdown';

export interface WoDetail {
  actintlabcost: number;
  actintlabhrs: number;
  actlabcost: number;
  actlabhrs: number;
  actmatcost: number;
  actoutlabcost: number;
  actoutlabhrs: number;
  actservcost: number;
  acttoolcost: number;
  ams: boolean;
  aos: boolean;
  apptrequired: boolean;
  assetnum: string;
  calcpriority: number;
  changeby: string;
  changedate: string;
  chargestore: boolean;
  cxactualdur: number;
  cxconfinedspace: boolean;
  cxdiving: boolean;
  cxenvironment: boolean;
  cxexcavation: boolean;
  cxhotwork: boolean;
  cxjracno: string;
  cxmainsystemtrip: boolean;
  cxplantlimitation: boolean;
  cxplantload: boolean;
  cxradiography: boolean;
  cxsafetypersonnel: boolean;
  cxworkatheight: boolean;
  cxworktobedone: string;
  department: string;
  department_description: string;
  description: string;
  disabled: boolean;
  djpapplied: string;
  downtime: boolean;
  em: boolean;
  estatapprintlabcost: number;
  estatapprintlabhrs: number;
  estatapprlabcost: number;
  estatapprlabhrs: number;
  estatapprmatcost: number;
  estatapproutlabcost: number;
  estatapproutlabhrs: number;
  estatapprservcost: number;
  estatapprtoolcost: number;
  estdur: number;
  estintlabcost: number;
  estintlabhrs: number;
  estlabcost: number;
  estlabhrs: number;
  estmatcost: number;
  estoutlabcost: number;
  estoutlabhrs: number;
  estservcost: number;
  esttoolcost: number;
  faildate: string;
  failurecode: string;
  flowactionassist: boolean;
  flowcontrolled: boolean;
  glaccount: string;
  haschildren: boolean;
  hasfollowupwork: boolean;
  historyflag: boolean;
  href: string;
  ignorediavail: boolean;
  ignoresrmavail: boolean;
  inctasksinsched: boolean;
  interruptible: boolean;
  invreserve_collectionref: string;
  invuse_collectionref: string;
  isshutdown: boolean;
  istask: boolean;
  iswarranty: boolean;
  lastcopylinkdate: string;
  lms: boolean;
  location: string;
  los: boolean;
  milestone: boolean;
  nestedjpinprocess: boolean;
  newchildclass: string;
  onbehalfof: string;
  organization: string;
  organization_description: string;
  orgid: string;
  outlabcost: number;
  outmatcost: number;
  outtoolcost: number;
  parentchgsstatus: boolean;
  permittype: string;
  permittype_description: string;
  phone: string;
  plantreliability: boolean;
  pluscismobile: boolean;
  pluscloop: boolean;
  problemcode: string;
  repairlocflag: boolean;
  reportdate: string;
  reportedby: string;
  reqasstdwntime: boolean;
  respondby: string;
  responsiblesection: string;
  responsiblesection_description: string;
  respsap: string;
  respsap_description: string;
  respwo: string;
  respwo_description: string;
  runningtest: boolean;
  safedoc: boolean;
  section: string;
  shutdowntype: string;
  shutdowntype_description: string;
  siteid: string;
  status: string;
  status_description: string;
  statuscommt: string;
  statusdate: string;
  statusiface: boolean;
  suspendflow: boolean;
  woacceptscharges: boolean;
  woclass: string;
  woclass_description: string;
  woeq1: string;
  wogroup: string;
  woisswap: boolean;
  wonum: string;
  wopriority: number;
  wopriority_description: string;
  workorderid: number;
  worktype: string;
  _rowstamp: string;
}

export interface PoDetailPoline {
  itemnum: string;
  _rowstamp: string;
  localref: string;
  description: string;
  orderqty: number;
  orderunit: string;
  href: string;
  polinenum: number;
  conditioncode: string;
  conversion: number;
}

export interface PoDetailWmsMatrectrans {
  rejectqty: number;
  itemnum: string;
  _rowstamp: string;
  receiptquantity: number;
  positeid: string;
  localref: string;
  description: string;
  orderunit: string;
  href: string;
  polinenum: number;
  orgid: string;
}

export interface PoDetail {
  status_description: string;
  revisionnum: number;
  orderdate: string;
  orgid: string;
  poid: number;
  matrectrans_collectionref: string;
  _rowstamp: string;
  vendor: string;
  poline_collectionref: string;
  wms_matrectrans: PoDetailWmsMatrectrans[];
  ponum: string;
  siteid: string;
  href: string;
  poline: PoDetailPoline[];
  wms_matrectrans_collectionref: string;
  status: string;
}

export interface SerializedItem {
  conditioncode: string;
  datemodified: string;
  description: string;
  href: string;
  itemnum: string;
  itemsetid: string;
  localref: string;
  matrectransid: number;
  orgid: string;
  qtyserialized: number;
  qtystored: number;
  unitserialized: string;
  unitstored: string;
  wms_serializeditemid: number;
}
